---

- name: Install Pip
  package:
    name: python3-pip
    state: present

- name: Install docker libs
  pip:
    state: present
    name: ['jsondiff', 'pyyaml']

- name: Create group
  group:
    name: "{{ services_group }}"
    state: present

- include_tasks: create_or_get_user.yml
