version: '3.5'



#x-base: &base
#  restart: unless-stopped
#  logging:
#    driver: "json-file"
#    options:
#      max-file: "1"
#      max-size: "2M"
#  ulimits:
#    nproc: 8192
#    nofile: 8192
#services:
#  caddy:
#    <<: *base
#    image: {{ services_oci_images_applications_caddy }}
#    command: ["caddy", "run", "-watch", "--config", "/config/Caddyfile", "--adapter", "caddyfile"]
#    ports:
#      - 80:80
#      - 443:443
#    networks:
#      - frontend
#    volumes:
#      - {{ services_storage_path }}:/git:ro
#      - {{ services_storage_path }}/gitlist:/gitlist:ro
#      - {{ services_storage_path }}/caddy:/etc/caddy
#      - {{ services_storage_path }}/caddy:/config
#  git-http-backend:
#    <<: *base
#    image: {{ services_oci_images_applications_git_http_backend }}
#    networks:
#      - backend
#    volumes:
#      - {{ services_storage_path }}:/git:ro
#  gitlist:
#    <<: *base
#    image: {{ services_oci_images_applications_php_with_git }}
#    networks:
#      - backend
#    volumes:
#      - {{ services_storage_path }}:/git:ro
#      - {{ services_storage_path }}/gitlist:/gitlist:ro
##  athens:
##    <<: *base
##    image: {{ services_oci_images_applications_athens }}
##    volumes:
##      - {{ services_config_path }}/athens:/config:ro
#  docker-registry:
#    <<: *base
#    image: {{ services_oci_images_applications_image_registry }}
#    networks:
#      - backend
#    volumes:
#      - {{ services_config_path }}/docker-registry:/etc/docker/registry:ro
