---

coredns_zone_origin: "in.tcry.pt"
coredns_zone_default_ttlive: 3600
coredns_zone_serial_epoch: 1231006505
coredns_forward_origins:
  - "172.98.193.42"
  - "46.21.150.56"
  - "155.138.240.237"

coredns_zone_primary_ns: "ns1"
coredns_zone_hostmaster: "mail.tcry.pt"
coredns_zone_serial: null
coredns_zone_ttrefresh: 7200
coredns_zone_ttretry: 3600
coredns_zone_ttexpire: 604800
coredns_zone_minimum_ttlive: 300


coredns_version: "1.8.0"
coredns_user: coredns
coredns_group: coredns
coredns_home: "/home/{{ coredns_user }}"

coredns_config_path: "/home/{{ coredns_user }}/config"
coredns_binary_path: "{{ coredns_home }}/bin"
coredns_binary_file: "{{ coredns_binary_path }}/coredns"
coredns_binary_src_path: "https://github.com/coredns/coredns/releases/download/v{{ coredns_version }}/coredns_{{ coredns_version }}_linux_amd64.tgz"

coredns_port: 53
coredns_health_port: 8080
coredns_prometheus_port: 9153

coredns_acl_allow:
  - 10.2.0.0/20

coredns_interface: "eth1"
