---

#- name: Download archive
#  get_url:
#    url: "{{ coredns_binary_src }}"
#    dest: "/tmp/coredns-{{ coredns_version }}.tar.gz"
#    mode: 0755
#    owner: "{{ coredns_user }}"
#    group: "{{ coredns_group }}"

- name: Extract binary
  unarchive:
    mode: 0755
    remote_src: yes
    src: "{{ coredns_binary_src_path }}"
    dest: "{{ coredns_binary_path }}"
    owner: "{{ coredns_user }}"
    group: "{{ coredns_group }}"

- name: Set capability to bind to privledged ports
  capabilities:
    path: "{{ coredns_binary_file }}"
    capability: cap_net_bind_service+ep
    state: present

- name: Add systemd unit file
  template:
    src: coredns.service
    dest: /etc/systemd/system/coredns.service
    mode: 0644
  notify: Restart coredns

- name: Set time as fact for our SOA serial
  debug:
    var=ansible_date_time

- name: Set serial to unix epoch
  set_fact:
    zone_serial: "{{ coredns_zone_serial or (ansible_date_time.epoch|int) - coredns_zone_serial_epoch }}"

- name: Copy config files
  template:
    src: "{{ item }}.j2"
    dest: "{{ coredns_config_path }}/{{ item }}"
    owner: "{{ coredns_user }}"
    group: "{{ coredns_group }}"
  notify: Restart coredns
  with_items:
    - Corefile
    - zone
    - zone-reverse
