---

- name: Create group
  group:
    name: "{{ coredns_group }}"
    state: present

- name: Create user
  user:
    state: present
    name: "{{ coredns_user }}"
    home: "{{ coredns_home }}"
    groups:
      - "{{ coredns_group }}"

- name: Allow DNS through UFW
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    interface: "{{ coredns_interface }}"
    direction: in
  with_items:
    - port: "53"
      proto: tcp
    - port: "53"
      proto: udp

- name: Create bin and config folders
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ coredns_user }}"
    group: "{{ coredns_group }}"
  with_items:
    - "{{ coredns_binary_path }}"
    - "{{ coredns_config_path }}"
    - "{{ coredns_config_path }}/zones"
