---
all:
  children:
    # First assign hosts to geographic areas
    local:
      hosts:
        local-workstation:
    sfo2:
      hosts:
        compute-worker-sfo2-1:
        compute-worker-sfo2-2:
    sgp1:
      hosts:
        compute-worker-sgp1-1:

    west:
      children:
        sfo2:
    east:
      children:
        sgp1:

    # Assign roles
    storage_server:
      hosts:
        compute-worker-sfo2-1:

    docker_swarm_manager:
      hosts:
        compute-worker-sfo2-1:
        compute-worker-sfo2-2:
        compute-worker-sgp1-1:
    docker_swarm_worker:
      hosts:
        compute-worker-sfo2-1:
        compute-worker-sfo2-2:
        compute-worker-sgp1-1:
    swarm:
      children:
        docker_swarm_manager:
        docker_swarm_worker:
