---
all:
  hosts:
    compute-beacon-1:
      region: sfo2
      ansible_host: 167.172.118.77
      ip_v4: 167.172.118.77
      ip_v6: 2604:a880:2:d1::e2:5001
      ip_vpc_v4: 10.2.0.4
    compute-worker-1:
      region: sfo2
      ansible_host: 64.225.44.93
      ip_v4: 64.225.44.93
      ip_v6: 2604:a880:2:d1::13e:7001
      ip_vpc_v4: 10.2.0.2
      storage_volume_id: scsi-0DO_Volume_storage-1
