---

- name: Install Pip
  package:
    name: python3-pip
    state: present

- name: Install docker libs
  pip:
    state: present
    name: ['setuptools', 'docker', 'docker-compose']

- name: Create group
  group:
    name: "{{ webserver_group }}"
    state: present

- name: Create user
  user:
    state: present
    name: "{{ webserver_user }}"
    home: "{{ webserver_home }}"
    groups:
      - "{{ webserver_group }}"
      - docker

- name: Allow http, https, http3 through UFW
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items:
    - port: "80"
      proto: tcp
    - port: "443"
      proto: tcp
    - port: "443"
      proto: udp

- name: Create directories to store configs, data, and src code
  file:
    state: directory
    dest: "{{ item }}"
    owner: "{{ webserver_user }}"
    group: "{{ webserver_group }}"
    mode: 0750
  with_items:
    - "{{ webserver_src_path }}"
    - "{{ webserver_src_path }}/gitlist"
    - "{{ webserver_data_path }}"
    - "{{ webserver_data_path }}/caddy"
    - "{{ webserver_config_path }}"
    - "{{ webserver_config_path }}/athens"
    - "{{ webserver_config_path }}/caddy"
    - "{{ webserver_config_path }}/docker"
    - "{{ webserver_config_path }}/docker-registry"
    - "{{ webserver_config_path }}/gitlist"
