---

- name: Initialize security
  hosts: all:!local
  become: true
  tags:
    - security
  vars:
    security_sudoers_passwordless: ["ansible"]
  roles:
    - geerlingguy.security

- name: Initialialize persitent storage
  hosts: storage
  become: true
  vars_files:
    - config/compute.yml
  tags:
    - storage
  roles:
    - name: tcrypt.storage
      storage_block_storage_volume_id: "{{ storage_volume_id }}"

- name: Initialialize gitserver
  hosts: compute[0]
  become: true
  vars_files:
    - config/compute.yml
  tags:
    - gitserver
  roles:
    - name: tcrypt.gitserver

- name: Initialialize webserver
  hosts: compute[0]
  become: true
  vars_files:
    - vault/compute.yml
    - config/compute.yml
  vars:
    webserver_athens_minio_key: "{{ vault_webserver_athens_minio_key }}"
    webserver_athens_minio_secret: "{{ vault_webserver_athens_minio_secret }}"
    webserver_athens_minio_bucket: "{{ vault_webserver_athens_minio_bucket }}"
    webserver_athens_minio_region: "{{ vault_webserver_athens_minio_region }}"
    webserver_athens_minio_endpoint: "{{ vault_webserver_athens_minio_endpoint }}"
  tags:
    - webserver
  roles:
    - name: geerlingguy.docker
    - name: tcrypt.webserver
