---

- name: Base
  hosts: all:!local
  become: true
  tags:
    - base
    - security
  vars_files:
    - config/vault/tailscale.yml
  vars:
    security_sudoers_passwordless: ["ansible"]
    tailscale_auth_key: "{{ vault_tailscale_auth_key }}"
  roles:
    - geerlingguy.security
    - artis3n.tailscale
  tasks:
    - name: Allow SSH through UFW
      community.general.ufw:
        rule: allow
        port: 22
        proto: tcp
    - name: Enable UFW with all ingress connections disabled by default
      community.general.ufw:
        state: enabled
        default: deny
        direction: incoming
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

- name: Storage
  hosts: storage
  become: true
  vars_files:
    - config/block_storage.yml
  tags:
    - storage
  roles:
    - name: tcrypt.tcry_pt.block_storage

- name: Create Swarm
  hosts: swarm
  become: true
  tags:
    - swarm
    - init
  roles:
    - tcrypt.tcry_pt.swarm_agent

- name: Deploy Services
  hosts: docker_swarm_manager[0]
  become: true
  tags:
    - swarm
    - services
  tasks:
    - include_role:
        name: tcrypt.tcry_pt.services
