---

- name: Initialialize persitent storage
  hosts: remote_compute
  become: true
  vars_files:
    - config/remote-compute.yml
  tags:
    - storage
  roles:
    - name: tcrypt.storage

- name: Initialialize gitserver
  hosts: gitserver
  become: true
  vars_files:
    - config/remote-compute.yml
  tags:
    - gitserver
  roles:
    - name: tcrypt.gitserver

- name: Initialialize webserver
  hosts: webserver
  become: true
  vars_files:
    - vault/remote-compute.yml
    - config/remote-compute.yml
  vars:
    webserver_athens_minio_key: "{{ vault_webserver_athens_minio_key }}"
    webserver_athens_minio_secret: "{{ vault_webserver_athens_minio_secret }}"
    webserver_athens_minio_bucket: "{{ vault_webserver_athens_minio_bucket }}"
    webserver_athens_minio_region: "{{ vault_webserver_athens_minio_region }}"
    webserver_athens_minio_endpoint: "{{ vault_webserver_athens_minio_endpoint }}"
  tags:
    - webserver
  roles:
    - name: geerlingguy.docker
    - name: tcrypt.webserver
