#!/usr/bin/env ruby

require 'json'

MODULE_NAME = "module.tcrypt"
INDENT_ENTRY = "    "
INDENT_VALUE = INDENT_ENTRY+"  "
VOLUME_NAME_PREFIX = "scsi-0DO_Volume_"

@state = JSON.parse(ARGF.read)['values']['root_module']['child_modules']
@resources = @state.find{|m| m['address'] == MODULE_NAME }['resources']
@volumes = @resources.select{|m| m['type'] == "digitalocean_volume" }
@volumes_by_id = Hash[*@volumes.flat_map{|v| [v['values']['id'], v]}]
@droplets = @resources.select{|m| m['type'] == "digitalocean_droplet" }

puts "---\nall:\n  hosts:\n"

@droplets.each do |m|
  v = m['values']
  name = v['name']

  entry = [
    "region: #{v['region']}",
    "ansible_host: #{v['ipv4_address']}",
    "ip_v4: #{v['ipv4_address']}",
    "ip_v6: #{v['ipv6_address']}",
    "ip_vpc_v4: #{v['ipv4_address_private']}",
  ]

  (v['volume_ids'] || [])[0,1].each do |volume_id|
    entry << "block_storage_volume_id: #{VOLUME_NAME_PREFIX}#{@volumes_by_id[volume_id]['values']['name']}"
  end

  puts "#{INDENT_ENTRY}#{name.gsub(/_/,"-")}:"
  puts INDENT_VALUE+entry.join("\n#{INDENT_VALUE}")
end

