---

collections:
  - name: community.general

roles:
  - name: geerlingguy.homebrew
  - name: geerlingguy.security
  - name: geerlingguy.docker
  - name: artis3n.tailscale
  - name: atosatto.docker-swarm
